name: Build and push docker images

# on:
#   push:
#     tags: [ '*.*.*' ]

# on:
#   - workflow_dispatch

on:
  - push

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        - dockerfile: ./Dockerfile
          context: .
          image: ghcr.io/${{ github.repository_owner }}/ya16sdb
        - dockerfile: ./dash/Dockerfile
          image: ghcr.io/${{ github.repository_owner }}/ya16sdb-app
          context: ./dash
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ env.RELEASE_VERSION }}
